// Generated by _build/build-explore.mjs — do not edit; edit
// _build/directives/*.js and rerun `npm run rebuild:explore`.
window.Directives = (function () {
  const registry = {}, cache = {};
  const define = (name, fn) => { registry[name] = fn; };
  const require = (name) => {
    name = name.replace(/^\.\//, '');
    if (!(name in cache)) {
      const module = { exports: {} };
      registry[name](module, require);
      cache[name] = module.exports;
    }
    return cache[name];
  };
  define("svg", function (module, require) {
'use strict';
// Shared SVG string helpers and the report palette.

const PAL = {
  cream: '#FBF8F1', ink: '#2b2b2b', sub: '#6a6453', faint: '#8a8170',
  grid: '#E3DDCE', green: '#1f7a3d', gold: '#B8860B', goldText: '#9a6f08',
  purple: '#7a4b8a', slate: '#5b7a99', ringFill: '#2e8b57',
  boundary: '#d9d2c0', townEdge: '#6a6453', hatchFill: '#efe9da',
  // Concentric-ring shades, darkest (core) outward; consistent across maps.
  rings: ['#1f7a3d', '#4f9c62', '#82bd8f', '#b5dcbc'],
};

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const attrs = o => Object.entries(o).map(([k, v]) => ` ${k}="${v}"`).join('');
const el = (tag, a, inner) =>
  inner == null ? `<${tag}${attrs(a)}/>` : `<${tag}${attrs(a)}>${inner}</${tag}>`;
const text = (x, y, s, a = {}) =>
  el('text', { x: r1(x), y: r1(y), ...a }, esc(s));
const poly = pts => pts.map(p => `${p[0]},${p[1]}`).join(' ');
const r1 = v => Math.round(v * 10) / 10;

module.exports = { PAL, esc, attrs, el, text, poly, r1 };

  });
  define("resolve", function (module, require) {
'use strict';
// Group resolution: membership -> included units, honest exclusions, aggregated series.

function resolveGroup(data, groupId) {
  const g = data.groups[groupId];
  if (!g) throw new Error(`Unknown group '${groupId}'`);
  const included = [], noLocal = [];
  for (const name of g.members) {
    const u = data.units[name];
    if (!u) { noLocal.push({ name, reason: 'not in dataset' }); continue; }
    if (u.type === 'town' && u.local_district === false) {
      noLocal.push({ name, regions: u.regions || [] });
      continue;
    }
    included.push(name);
  }
  // A town with no local district is only truly excluded when no included
  // regional district covers it; a covered town (e.g. Haddam once Region 17
  // joins) is fully represented through that region.
  const coveredBy = name => included.find(n => {
    const u = data.units[n];
    return u.type === 'region' && (u.members || []).includes(name);
  });
  const excluded = [], represented = [];
  for (const e of noLocal) {
    const via = coveredBy(e.name);
    if (via) represented.push({ name: e.name, via });
    else excluded.push({ name: e.name,
      reason: e.reason || (e.regions.length
        ? `no local district; member of ${e.regions.join(', ')}`
        : 'no local district') });
  }
  return { id: groupId, label: g.label, definition: g.definition || '',
           included, excluded, represented };
}

// weighting: 'enrollment' (combined exp / combined enr). 'equal' reserved.
function seriesFor(data, resolved, fy0, fy1, weighting) {
  if (weighting && weighting !== 'enrollment')
    throw new Error(`weighting '${weighting}' not implemented (v1 supports 'enrollment')`);
  const yi = new Map(data.years.map((y, i) => [y, i]));
  const rows = [];
  for (let y = fy0; y <= fy1; y++) {
    const i = yi.get(y);
    if (i === undefined) continue;
    let enr = 0, exp = 0, ok = true;
    for (const name of resolved.included) {
      const u = data.units[name];
      const e = u.enr && u.enr[i], x = u.exp && u.exp[i];
      if (e == null || x == null) { ok = false; break; }
      enr += e; exp += x;
    }
    if (ok && enr > 0) rows.push({ fy: y, enr, exp, pp: exp / enr });
  }
  if (!rows.length) throw new Error(`No complete years for '${resolved.id}' in ${fy0}-${fy1}`);
  return rows;
}

module.exports = { resolveGroup, seriesFor };

  });
  define("decomp", function (module, require) {
'use strict';
// <% decomp <group> [window=FY0:FY1] [weighting=enrollment] %>
// Renders the four-line decomposition chart (per-pupil, spending, enrollment,
// CPI, cumulative % since the window's first year) as an inline SVG string.

const { PAL, el, text, poly, r1 } = require('./svg');
const { resolveGroup, seriesFor } = require('./resolve');

const FW = 960, FH = 640;                       // frame
const M = { l: 58, r: 190, t: 96, b: 44 };      // margins (right holds labels)

function decomp(ctx, groupId, args = {}) {
  const { data, cpi } = ctx;
  const g = resolveGroup(data, groupId);
  let [fy0, fy1] = (args.window || '2013:2023').split(':').map(Number);
  const rows = seriesFor(data, g, fy0, fy1, args.weighting || 'enrollment');
  fy0 = rows[0].fy; fy1 = rows[rows.length - 1].fy;

  const base = rows[0];
  const cum = f => rows.map(r => (f(r) / f(base) - 1) * 100);
  const pp = cum(r => r.pp), sp = cum(r => r.exp), en = cum(r => r.enr);
  const cp = rows.map(r => (cpi.values[r.fy] / cpi.values[fy0] - 1) * 100);

  const lo = Math.min(0, ...en, ...sp), hi = Math.max(...pp, ...sp, ...cp);
  const pad = (hi - lo) * 0.10;
  const y0 = lo - pad, y1 = hi + pad;
  const X = fy => M.l + (fy - fy0) / (fy1 - fy0) * (FW - M.l - M.r);
  const Y = v => M.t + (y1 - v) / (y1 - y0) * (FH - M.t - M.b);
  const pts = arr => rows.map((r, i) => [r1(X(r.fy)), r1(Y(arr[i]))]);

  const out = [];
  out.push(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${FW} ${FH}" ` +
    `font-family="Georgia,serif" role="img" aria-label="${g.label}: spending, students, and inflation">`);
  out.push(el('rect', { width: FW, height: FH, fill: PAL.cream }));

  // gridlines + y ticks (steps of 10 or 20 depending on range)
  const step = (y1 - y0) > 120 ? 20 : 10;
  for (let v = Math.ceil(y0 / step) * step; v <= y1; v += step) {
    out.push(el('line', { x1: M.l, x2: FW - M.r, y1: r1(Y(v)), y2: r1(Y(v)),
      stroke: PAL.grid, 'stroke-width': 1 }));
    out.push(text(M.l - 8, Y(v) + 4, (v > 0 ? '+' : '') + v + '%',
      { 'text-anchor': 'end', 'font-size': 12, fill: '#5a5446' }));
  }
  // enrollment shading, zero line
  out.push(el('polygon', { points: poly([[X(fy0), Y(0)], ...pts(en), [X(fy1), Y(0)]]),
    fill: PAL.slate, opacity: 0.10 }));
  out.push(el('line', { x1: M.l, x2: FW - M.r, y1: r1(Y(0)), y2: r1(Y(0)),
    stroke: PAL.faint, 'stroke-width': 1.2 }));

  // series
  const line = (arr, stroke, w, dash) =>
    el('polyline', { points: poly(pts(arr)), fill: 'none', stroke,
      'stroke-width': w, ...(dash ? { 'stroke-dasharray': dash } : {}) });
  out.push(line(sp, PAL.gold, 3, '9,5'));
  out.push(line(cp, PAL.purple, 2.6, '2.5,4'));
  out.push(line(en, PAL.slate, 3.2));
  pts(en).forEach(p => out.push(el('rect',
    { x: p[0] - 3.4, y: p[1] - 3.4, width: 6.8, height: 6.8,
      fill: PAL.slate, stroke: '#fff', 'stroke-width': 1.1 })));
  out.push(line(pp, PAL.green, 4.2));
  pts(pp).forEach(p => out.push(el('circle',
    { cx: p[0], cy: p[1], r: 4.6, fill: PAL.green, stroke: '#fff', 'stroke-width': 1.2 })));

  // x axis labels
  for (const r of rows)
    out.push(text(X(r.fy), FH - M.b + 22, 'FY' + r.fy,
      { 'text-anchor': 'middle', 'font-size': 11.5, fill: '#5a5446' }));

  // end labels with simple collision spreading
  const last = a => a[a.length - 1];
  const fmt = (v, sign = true) => (sign && v >= 0 ? '+' : '') + Math.round(v) + '%';
  const labels = [
    { v: last(pp), t: `Per-pupil  ${fmt(last(pp))}`, c: PAL.green, s: 15, w: 'bold' },
    { v: last(sp), t: `Total spending  ${fmt(last(sp))}`, c: PAL.goldText, s: 13.5, w: 'bold' },
    { v: last(cp), t: `Inflation  ${fmt(last(cp))}`, c: PAL.purple, s: 13.5, w: 'bold' },
    { v: last(en), t: `Enrollment  ${fmt(last(en))}`, c: PAL.slate, s: 13.5, w: 'bold' },
  ].sort((a, b) => b.v - a.v);
  const minGap = 20;
  let ys = labels.map(l => Y(l.v));
  for (let i = 1; i < ys.length; i++)
    if (ys[i] - ys[i - 1] < minGap) ys[i] = ys[i - 1] + minGap;
  labels.forEach((l, i) => out.push(text(FW - M.r + 12, ys[i] + 5, l.t,
    { 'font-size': l.s, 'font-weight': l.w, fill: l.c,
      'font-family': 'Verdana,Geneva,sans-serif' })));

  // titles + source line
  out.push(text(12, 30, `${g.label}`, { 'font-size': 22, 'font-weight': 'bold', fill: PAL.ink,
    'font-family': 'Verdana,Geneva,sans-serif' }));
  out.push(text(12, 54,
    `Cumulative change since FY${fy0}: per-pupil cost, total current spending, enrollment, and inflation`,
    { 'font-size': 12.5, fill: PAL.sub }));
  out.push(text(12, FH - 10,
    'Sources: NCES/Census F-33 (NCES basis; includes state-paid teacher retirement) \u00b7 BLS CPI-U, July\u2013June averages',
    { 'font-size': 10, fill: PAL.faint }));
  out.push('</svg>');
  return out.join('');
}

module.exports = decomp;

  });
  define("locmap", function (module, require) {
'use strict';
// <% locmap <group> %>
// Locator map: full CT with the group's towns highlighted. Coloring: included
// towns fill green, shaded by concentric ring (darkest at the innermost nested
// group, lighter with each ring, consistent across maps); towns counted only
// through an included regional district fill slate; excluded group towns are
// hatched. Borders between highlighted towns use the chart background so
// adjacent fills stay distinct.

const { PAL, el, poly, text, r1 } = require('./svg');
const { resolveGroup } = require('./resolve');

const FW = 960, FH = 500;

function classify(data, g) {
  const local = new Set(), viaRegion = new Set(), hatched = new Set();
  for (const name of g.included.concat(g.excluded.map(e => e.name))) {
    const u = data.units[name];
    if (!u) continue;
    if (u.type === 'region') for (const m of u.members || []) viaRegion.add(m);
  }
  for (const name of g.included)
    if (data.units[name].type === 'town') local.add(name);
  for (const e of g.excluded) hatched.add(e.name);
  return { local, viaRegion, hatched };
}

// The chain of named groups strictly nested inside this one (smallest first,
// the group itself last), e.g. core -> block1 -> block2 for block2. Only
// multi-member groups count, and the candidates must nest cleanly; otherwise
// there is no ring structure and the map uses a single fill.
function ringChain(data, groupId) {
  const cur = data.groups[groupId];
  if (!cur || !cur.members) return null;
  const curSet = new Set(cur.members);
  const subset = (a, b) => a.size < b.size && [...a].every(x => b.has(x));
  const cands = Object.entries(data.groups)
    .filter(([id, gr]) => id !== groupId && gr.members && gr.members.length > 1)
    .map(([id, gr]) => new Set(gr.members))
    .filter(s => subset(s, curSet))
    .sort((a, b) => a.size - b.size);
  if (!cands.length) return null;
  for (let i = 1; i < cands.length; i++)
    if (!subset(cands[i - 1], cands[i])) return null;
  return [...cands, curSet];
}

function locmap(ctx, groupId) {
  const { data, geo } = ctx;
  const g = resolveGroup(data, groupId);
  if (g.included.some(n => data.units[n].type === 'state'))
    return stateMap(ctx, g);
  const { local, viaRegion, hatched } = classify(data, g);
  const tiers = ringChain(data, groupId);
  const shade = t => {
    if (!tiers) return PAL.green;
    for (let i = 0; i < tiers.length; i++)
      if (tiers[i].has(t)) return PAL.rings[Math.min(i, PAL.rings.length - 1)];
    return PAL.rings[PAL.rings.length - 1];
  };
  const color = t =>
    hatched.has(t) ? null :
    local.has(t) ? shade(t) :
    viaRegion.has(t) ? PAL.slate : undefined;

  // geometry space -> frame
  const sw = geo.viewW, sh = geo.viewH;
  const s = Math.min((FW - 40) / sw, (FH - 70) / sh);
  const ox = (FW - sw * s) / 2, oy = 56 + (FH - 70 - sh * s) / 2;
  const P = pt => [r1(pt[0] * s + ox), r1(pt[1] * s + oy)];

  const out = [];
  out.push(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${FW} ${FH}" ` +
    `font-family="Verdana,Geneva,sans-serif" role="img" aria-label="Map: ${g.label}">`);
  out.push('<defs><pattern id="hatch" width="6" height="6" patternTransform="rotate(45)" patternUnits="userSpaceOnUse">' +
    `<rect width="6" height="6" fill="${PAL.hatchFill}"/>` +
    '<line x1="0" y1="0" x2="0" y2="6" stroke="#a99f8a" stroke-width="1.4"/></pattern></defs>');
  out.push(el('rect', { width: FW, height: FH, fill: PAL.cream }));
  for (const [n, rings] of Object.entries(geo.coarse || geo.towns)) {
    const c = color(n);
    for (const ring of rings) {
      const pp = ring.map(P);
      if (c) out.push(el('polygon', { points: poly(pp), fill: c,
        stroke: PAL.cream, 'stroke-width': 0.6 }));
      else if (hatched.has(n)) out.push(el('polygon', { points: poly(pp),
        fill: 'url(#hatch)', stroke: PAL.cream, 'stroke-width': 0.6 }));
      else out.push(el('polygon', { points: poly(pp), fill: 'none',
        stroke: PAL.boundary, 'stroke-width': 0.35 }));
    }
  }
  for (const ring of geo.state)
    out.push(el('polygon', { points: poly(ring.map(P)),
      fill: 'none', stroke: PAL.faint, 'stroke-width': 1.1 }));
  out.push(text(12, 30, g.label, { 'font-size': 20, 'font-weight': 'bold', fill: PAL.ink }));
  out.push('</svg>');
  return out.join('');
}

function stateMap(ctx, g) {
  const { geo } = ctx;
  const { PAL: P } = require('./svg');
  const FW2 = 960, FH2 = 500;
  const sw = geo.viewW, sh = geo.viewH;
  const s = Math.min((FW2 - 40) / sw, (FH2 - 70) / sh);
  const ox = (FW2 - sw * s) / 2, oy = 56 + (FH2 - 70 - sh * s) / 2;
  const T = pt => `${r1(pt[0] * s + ox)},${r1(pt[1] * s + oy)}`;
  const out = [];
  out.push(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${FW2} ${FH2}" ` +
    `font-family="Verdana,Geneva,sans-serif" role="img" aria-label="Map: ${g.label}">`);
  out.push(el('rect', { width: FW2, height: FH2, fill: P.cream }));
  const src = geo.coarse || geo.towns;
  for (const rings of Object.values(src))
    for (const ring of rings)
      out.push(el('polygon', { points: ring.map(T).join(' '),
        fill: '#dceadf', stroke: '#b9cfc0', 'stroke-width': 0.4 }));
  for (const ring of geo.state)
    out.push(el('polygon', { points: ring.map(T).join(' '),
      fill: 'none', stroke: P.faint, 'stroke-width': 1.3 }));
  out.push(text(12, 30, g.label, { 'font-size': 20, 'font-weight': 'bold', fill: P.ink }));
  out.push('</svg>');
  return out.join('');
}

module.exports = locmap;

  });
  define("datatable", function (module, require) {
'use strict';
// <% datatable <group> [window=FY0:FY1] [basis=skip] %>
// Emits an aligned markdown table plus the Notes blockquote. By default the
// Notes open with the shared data-basis sentence so each table is
// self-contained (the mode a standalone generator wants); basis=skip omits it
// for documents that state the basis once in their methodology, and the
// blockquote disappears entirely when no group-specific notes remain.

const { resolveGroup, seriesFor } = require('./resolve');
const money = v => '$' + Math.round(v).toLocaleString('en-US');
const num = v => v.toLocaleString('en-US');

function datatable(ctx, groupId, args = {}) {
  const { data } = ctx;
  const g = resolveGroup(data, groupId);
  const [fy0, fy1] = (args.window || '2013:2023').split(':').map(Number);
  const rows = seriesFor(data, g, fy0, fy1, 'enrollment');

  const header = ['Fiscal year', 'School year', 'Students', 'Total current spending', 'Per pupil'];
  const body = rows.map(r => [String(r.fy),
    `${r.fy - 1}-${String(r.fy).slice(2)}`, num(r.enr), money(r.exp), money(r.pp)]);
  const w = header.map((h, i) => Math.max(h.length, ...body.map(b => b[i].length)));
  const pad = (s, i) => i >= 2 ? s.padStart(w[i]) : s.padEnd(w[i]);
  const line = cells => '| ' + cells.map(pad).join(' | ') + ' |';
  const rule = '|' + w.map((n, i) =>
    (i >= 2 ? '-'.repeat(n + 1) + ':' : '-'.repeat(n + 2))).join('|') + '|';

  const md = [line(header), rule, ...body.map(line)].join('\n');
  const parts = [];
  if (args.basis !== 'skip')
    parts.push(`${data.basis} Per pupil is combined spending divided ` +
      'by combined students, which weights each district by its enrollment.');
  if (g.represented && g.represented.length)
    parts.push(g.represented.map(r =>
      `${r.name} has no local district but is fully represented through ` +
      `${r.via}, included above`).join('; ') + '.');
  if (g.excluded.length)
    parts.push('Excluded from the aggregate: ' + g.excluded.map(e =>
      `${e.name} (${e.reason})`).join('; ') + '.');
  if (!parts.length) return md;
  return md + '\n\n' + `> **Notes:** ${parts.join(' ')}`;
}

module.exports = datatable;

  });
  return {
    ...require('resolve'),
    decomp: require('decomp'),
    locmap: require('locmap'),
    datatable: require('datatable'),
    PAL: require('svg').PAL,
  };
})();