#!/usr/bin/env node
/*
 * Build the per-pupil-trends exploration tool's generated assets:
 *
 *   explore/directives.js  — the site's vendored directive renderers
 *                            (svg, resolve, decomp, locmap, datatable)
 *                            wrapped for the browser as window.Directives,
 *                            so the tool and the report share one code path.
 *   explore/geo.json       — coarse town geometry + state outline + the
 *                            land-adjacency graph derived from it.
 *
 * The adjacency graph is validated against the report's block definitions
 * before anything is written: growing rings from the core must reproduce
 * block1/2/3's town membership exactly, or the build fails.
 *
 *   npm run rebuild:explore
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const HERE = import.meta.dirname;
const REPORT = join(HERE, "..", "reports", "ahm", "per-pupil-trends");
const OUT = join(REPORT, "explore");
mkdirSync(OUT, { recursive: true });

const geo = JSON.parse(readFileSync(join(REPORT, "towns_xy.json"), "utf8"));
const data = JSON.parse(readFileSync(join(REPORT, "dataset.json"), "utf8"));

// Land adjacency comes from the pipeline (TIGER boundaries with mapped water
// erased — see _pipeline/scripts/build_adjacency.py). The display geometry
// keeps river-centerline arcs, so it cannot be used to derive adjacency.
const adjacency = JSON.parse(
  readFileSync(join(REPORT, "_pipeline", "adjacency.json"), "utf8"));

// ---------------------------------------------------------------------------
// Validate: rings grown from the core must reproduce the block definitions.
// ---------------------------------------------------------------------------

const townsOf = (gid) =>
  new Set(data.groups[gid].members.filter((m) => data.units[m]?.type === "town"));
const growRing = (sel) => {
  const next = new Set(sel);
  for (const t of sel) for (const n of adjacency[t] || []) next.add(n);
  return next;
};

const core = townsOf("core");
let ring = core;
const expect = ["block1", "block2", "block3"];
for (const gid of expect) {
  ring = growRing(ring);
  const want = townsOf(gid);
  const extra = [...ring].filter((t) => !want.has(t));
  const missing = [...want].filter((t) => !ring.has(t));
  if (extra.length || missing.length) {
    console.error(`adjacency validation FAILED at ${gid}:`);
    if (extra.length) console.error(`  ring has extra towns: ${extra.join(", ")}`);
    if (missing.length) console.error(`  ring is missing: ${missing.join(", ")}`);
    process.exit(1);
  }
  console.log(`adjacency ✓ ring reproduces ${gid} (${want.size} towns)`);
}

// ---------------------------------------------------------------------------
// Emit geo.json (coarse + state + adjacency; the full-res layer stays home).
// ---------------------------------------------------------------------------

const geoOut = {
  viewW: geo.viewW,
  viewH: geo.viewH,
  coarse: geo.coarse,
  state: geo.state,
  adjacency,
};
writeFileSync(join(OUT, "geo.json"), JSON.stringify(geoOut));
console.log(`wrote explore/geo.json (${(JSON.stringify(geoOut).length / 1024).toFixed(0)} KB)`);

// ---------------------------------------------------------------------------
// Bundle the directive modules for the browser. They are dependency-free
// CommonJS; a minimal define/require shim is all the wrapping they need.
// ---------------------------------------------------------------------------

const MODULES = ["svg", "resolve", "decomp", "locmap", "datatable"];
const parts = [];
parts.push("// Generated by _build/build-explore.mjs — do not edit; edit");
parts.push("// _build/directives/*.js and rerun `npm run rebuild:explore`.");
parts.push("window.Directives = (function () {");
parts.push("  const registry = {}, cache = {};");
parts.push("  const define = (name, fn) => { registry[name] = fn; };");
parts.push("  const require = (name) => {");
parts.push("    name = name.replace(/^\\.\\//, '');");
parts.push("    if (!(name in cache)) {");
parts.push("      const module = { exports: {} };");
parts.push("      registry[name](module, require);");
parts.push("      cache[name] = module.exports;");
parts.push("    }");
parts.push("    return cache[name];");
parts.push("  };");
for (const name of MODULES) {
  const src = readFileSync(join(HERE, "directives", `${name}.js`), "utf8");
  parts.push(`  define(${JSON.stringify(name)}, function (module, require) {`);
  parts.push(src);
  parts.push("  });");
}
parts.push("  return {");
parts.push("    ...require('resolve'),");
parts.push("    decomp: require('decomp'),");
parts.push("    locmap: require('locmap'),");
parts.push("    datatable: require('datatable'),");
parts.push("    PAL: require('svg').PAL,");
parts.push("  };");
parts.push("})();");
writeFileSync(join(OUT, "directives.js"), parts.join("\n"));
console.log("wrote explore/directives.js");
